CREATE EXTENSION IF NOT EXISTS vector;

DO $$
BEGIN
  EXECUTE format('ALTER DATABASE %I SET timezone TO ''Asia/Seoul''', current_database());
EXCEPTION WHEN insufficient_privilege THEN
  RAISE NOTICE '타임존 설정 생략 (owner 아님)';
END $$;

CREATE TABLE IF NOT EXISTS companies (
    id                   BIGSERIAL PRIMARY KEY,
    name                 TEXT NOT NULL,
    ticker               VARCHAR(20),
    corp_code            TEXT,
    is_listed            BOOLEAN NOT NULL,
    description          TEXT,
    description_source   TEXT,
    description_rcept_no TEXT,
    wikidata_qid         TEXT,
    ceo_name             TEXT,
    country              TEXT NOT NULL,
    industry_code        TEXT,
    established_on       DATE,
    fiscal_month         TEXT,
    homepage             TEXT,
    address              TEXT,
    delisted_at          DATE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS companies_active_ticker_uk
  ON companies (ticker) WHERE delisted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_corp_code_uk
  ON companies (corp_code) WHERE corp_code IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS companies_wikidata_uk
  ON companies (wikidata_qid) WHERE wikidata_qid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_companies_name ON companies (name);
CREATE INDEX IF NOT EXISTS companies_country_idx ON companies (country);

CREATE TABLE IF NOT EXISTS company_aliases (
    id         BIGSERIAL PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    alias      TEXT   NOT NULL,
    lang       TEXT,
    source     TEXT   NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (alias, company_id)
);

CREATE INDEX IF NOT EXISTS company_aliases_alias_idx   ON company_aliases (alias);
CREATE INDEX IF NOT EXISTS company_aliases_company_idx ON company_aliases (company_id);

CREATE TABLE IF NOT EXISTS company_financials (
    id                BIGSERIAL PRIMARY KEY,
    company_id        BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    source            TEXT NOT NULL,
    fiscal_yymm       TEXT NOT NULL,
    period_type       TEXT NOT NULL,
    fs_div            TEXT,
    disclosed_at      DATE,
    rcept_no          TEXT,
    revenue           BIGINT,
    operating_income  BIGINT,
    net_income        BIGINT,
    roe               NUMERIC,
    eps               NUMERIC,
    bps               NUMERIC,
    total_assets      BIGINT,
    total_liabilities BIGINT,
    total_equity      BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS company_financials_uk
    ON company_financials (company_id, source, fs_div, fiscal_yymm, period_type, COALESCE(rcept_no, ''));

CREATE INDEX IF NOT EXISTS company_financials_lookup_idx
    ON company_financials (company_id, period_type, fiscal_yymm DESC);

CREATE TABLE IF NOT EXISTS stocks (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 TEXT NOT NULL,
    ticker               TEXT NOT NULL,
    market               TEXT NOT NULL,
    company_id           BIGINT REFERENCES companies (id),
    standard_code        TEXT NOT NULL,
    listed_date          DATE,
    delisted_at          DATE,
    is_active            BOOLEAN NOT NULL DEFAULT true,
    trading_suspended    BOOLEAN NOT NULL DEFAULT false,
    under_administration BOOLEAN NOT NULL DEFAULT false,
    delisting_trade      BOOLEAN NOT NULL DEFAULT false,
    listed_shares        BIGINT,
    par_value            NUMERIC,
    capital              BIGINT,
    source               TEXT NOT NULL DEFAULT 'KIS_MASTER',
    security_group       TEXT,
    preferred_stock      BOOLEAN NOT NULL DEFAULT false,
    etp                  BOOLEAN NOT NULL DEFAULT false,
    spac                 BOOLEAN NOT NULL DEFAULT false,
    inactive_at          TIMESTAMPTZ,
    raw_attributes       JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    synced_at            TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS stocks_standard_code_uk ON stocks (standard_code);
CREATE UNIQUE INDEX IF NOT EXISTS stocks_active_ticker_uk ON stocks (ticker) WHERE is_active;
CREATE INDEX IF NOT EXISTS stocks_company_id_idx ON stocks (company_id);
CREATE INDEX IF NOT EXISTS stocks_security_group_idx ON stocks (security_group);

CREATE TABLE IF NOT EXISTS service_companies (
    company_id BIGINT PRIMARY KEY REFERENCES companies (id) ON DELETE CASCADE,
    name       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_candles_daily (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date  DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,
    trade_value BIGINT,
    source      TEXT    NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, trade_date)
);

CREATE INDEX IF NOT EXISTS stock_candles_daily_date_idx ON stock_candles_daily (trade_date);

CREATE TABLE IF NOT EXISTS stock_candles_period (
    stock_id    BIGINT  NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    period      TEXT    NOT NULL,
    base_date   DATE    NOT NULL,
    open        NUMERIC NOT NULL,
    high        NUMERIC NOT NULL,
    low         NUMERIC NOT NULL,
    close       NUMERIC NOT NULL,
    volume      BIGINT  NOT NULL,
    trade_value BIGINT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, period, base_date)
);

CREATE TABLE IF NOT EXISTS stock_investor_flows (
    stock_id            BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date          DATE   NOT NULL,
    individual_net_qty  BIGINT,
    institution_net_qty BIGINT,
    foreign_net_qty     BIGINT,
    foreign_hold_ratio  NUMERIC,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (stock_id, trade_date)
);

CREATE TABLE IF NOT EXISTS stock_dividends (
    listing_id  BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    record_date DATE   NOT NULL,
    divi_kind   TEXT   NOT NULL,
    dps         NUMERIC,
    pay_date    DATE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (listing_id, record_date, divi_kind)
);

CREATE TABLE IF NOT EXISTS stock_valuations_daily (
    listing_id     BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    trade_date     DATE   NOT NULL,
    market_cap     BIGINT,
    per            NUMERIC,
    pbr            NUMERIC,
    eps            NUMERIC,
    bps            NUMERIC,
    dividend_yield NUMERIC,
    r_1w           NUMERIC,
    r_1m           NUMERIC,
    r_3m           NUMERIC,
    PRIMARY KEY (listing_id, trade_date)
);

CREATE TABLE IF NOT EXISTS news (
    id                  BIGSERIAL PRIMARY KEY,
    title               TEXT,
    text                TEXT,
    summary             TEXT,
    link                TEXT UNIQUE,
    originallink        TEXT,
    published_at        TIMESTAMPTZ,
    collected_at        TIMESTAMPTZ DEFAULT now(),
    is_processed        BOOLEAN NOT NULL DEFAULT FALSE,
    relation_extracted  BOOLEAN,
    cluster_rep_news_id BIGINT REFERENCES news (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_news_cluster_rep ON news (cluster_rep_news_id);
CREATE INDEX IF NOT EXISTS idx_news_unprocessed
  ON news (id) WHERE NOT is_processed;

CREATE TABLE IF NOT EXISTS news_companies (
    id         BIGSERIAL PRIMARY KEY,
    news_id    BIGINT NOT NULL REFERENCES news (id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (news_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_news_companies_news    ON news_companies (news_id);
CREATE INDEX IF NOT EXISTS idx_news_companies_company ON news_companies (company_id);

CREATE TABLE IF NOT EXISTS themes (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS theme_stocks (
    id       BIGSERIAL PRIMARY KEY,
    theme_id BIGINT NOT NULL REFERENCES themes (id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    reason   TEXT,
    UNIQUE (theme_id, stock_id)
);

CREATE INDEX IF NOT EXISTS theme_stocks_theme_idx ON theme_stocks (theme_id);
CREATE INDEX IF NOT EXISTS theme_stocks_stock_idx ON theme_stocks (stock_id);

CREATE TABLE IF NOT EXISTS search_keywords (
    id               BIGSERIAL PRIMARY KEY,
    keyword          TEXT NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_searched_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_search_keywords_last_searched
  ON search_keywords (last_searched_at);

INSERT INTO search_keywords (keyword)
VALUES
    ('특징주,공급'), ('특징주,계약'), ('특징주,수주'), ('특징주,납품')
ON CONFLICT (keyword) DO NOTHING;

CREATE TABLE IF NOT EXISTS disclosures (
    id                     BIGSERIAL PRIMARY KEY,
    rcept_no               TEXT NOT NULL,
    corp_code              TEXT NOT NULL,
    company_id             BIGINT REFERENCES companies (id),
    ticker                 VARCHAR(20),
    corp_cls               TEXT,
    report_nm              TEXT NOT NULL,
    is_correction          BOOLEAN NOT NULL DEFAULT false,
    correction_target_report TEXT,
    correction_target_date DATE,
    correction_reason      TEXT,
    original_rcept_no      TEXT,
    rcept_dt               DATE NOT NULL,
    flr_nm                 TEXT,
    link                   TEXT NOT NULL,
    contract_type          TEXT,
    contract_name          TEXT,
    counterparty           TEXT,
    counterparty_corp_name TEXT,
    counterparty_corp_code TEXT,
    counterparty_ticker    VARCHAR(20),
    start_date             DATE,
    end_date               DATE,
    order_date             DATE,
    fields                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    meta                   JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS disclosures_rcept_no_uk ON disclosures (rcept_no);
CREATE INDEX IF NOT EXISTS disclosures_company_id_idx ON disclosures (company_id);
CREATE INDEX IF NOT EXISTS disclosures_rcept_dt_idx ON disclosures (rcept_dt);
CREATE INDEX IF NOT EXISTS disclosures_report_nm_idx ON disclosures (report_nm);

CREATE INDEX IF NOT EXISTS disclosures_counterparty_corp_code_idx
  ON disclosures (counterparty_corp_code) WHERE counterparty_corp_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS disclosures_counterparty_company_idx
  ON disclosures (((fields ->> 'counterparty_company_id')::bigint))
  WHERE fields ->> 'counterparty_company_id' IS NOT NULL;

CREATE INDEX IF NOT EXISTS disclosures_corp_code_rcept_dt_idx
  ON disclosures (corp_code, rcept_dt);
CREATE INDEX IF NOT EXISTS disclosures_original_rcept_no_idx
  ON disclosures (original_rcept_no) WHERE original_rcept_no IS NOT NULL;

CREATE TABLE IF NOT EXISTS relation_sources (
    id            BIGSERIAL PRIMARY KEY,

    source_type   TEXT NOT NULL CHECK (source_type IN ('news', 'disclosure')),
    news_id       BIGINT REFERENCES news (id) ON DELETE CASCADE,
    rcept_no      TEXT REFERENCES disclosures (rcept_no),

    subject_name  TEXT NOT NULL,
    subject_type  VARCHAR(20) NOT NULL DEFAULT 'COMPANY',
    subject_code  VARCHAR(20),
    relation      VARCHAR(30) NOT NULL,
    object_name   TEXT NOT NULL,
    object_type   VARCHAR(20) NOT NULL DEFAULT 'COMPANY',
    object_code   VARCHAR(20),

    evidence      TEXT,
    mentioned_at  DATE NOT NULL,
    item          TEXT,

    source_sentence TEXT,

    polarity        TEXT,
    tense           TEXT,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_relsrc_news_key       CHECK ((source_type = 'news')       = (news_id  IS NOT NULL)),
    CONSTRAINT chk_relsrc_disclosure_key CHECK ((source_type = 'disclosure') = (rcept_no IS NOT NULL)),

    CONSTRAINT uq_relsrc_news       UNIQUE (news_id,  subject_name, relation, object_name),
    CONSTRAINT uq_relsrc_disclosure UNIQUE (rcept_no, subject_name, relation, object_name)
);

CREATE INDEX IF NOT EXISTS idx_relsrc_edge
    ON relation_sources (subject_name, relation, object_name, mentioned_at DESC);

CREATE INDEX IF NOT EXISTS idx_relsrc_subject_code
    ON relation_sources (subject_code) WHERE subject_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_object_code
    ON relation_sources (object_code) WHERE object_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_subject_name ON relation_sources (subject_name);
CREATE INDEX IF NOT EXISTS idx_relsrc_object_name  ON relation_sources (object_name);

CREATE INDEX IF NOT EXISTS idx_relsrc_news     ON relation_sources (news_id)  WHERE news_id  IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relsrc_rcept_no ON relation_sources (rcept_no) WHERE rcept_no IS NOT NULL;

CREATE OR REPLACE VIEW entities_relations AS
SELECT subject_name, subject_type, relation, object_name, object_type,
       count(*) FILTER (WHERE source_type = 'news')       AS news_mention_count,
       count(*) FILTER (WHERE source_type = 'disclosure') AS disclosure_count,
       min(mentioned_at) AS first_mentioned_at,
       max(mentioned_at) AS last_mentioned_at
FROM relation_sources
GROUP BY 1, 2, 3, 4, 5;

CREATE INDEX IF NOT EXISTS idx_news_visible
  ON news (published_at DESC NULLS LAST, id DESC)
  WHERE is_processed AND relation_extracted;
