spring:
  application:
    name: backend-server

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    maximum-pool-size: 10

app:
  datasource:
    url: ${APP_DATASOURCE_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
    maximum-pool-size: 5

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


---
spring:
  config:
    activate:
      on-profile: local

management:
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
